version: 2.0-alpha
url: 
logo: /images/theme-icon.svg
slogan: Bazinga, theme cutie!
# Configure navigation menu, provide a relative link and a path to icon (icon should better be square)

# As long as the name matches the font awesome icon name, you can add even more social links
# As the tip: the social link can be a QRCODE link

global:
  comment_system: valine # disqus, valine, gitment
  scheme: Taurus
  icon_set: blue-line
  use_animation: true

post:
  allow_share: true
  allow_modification: false
  allow_commercial: false
  use_lightgallery: true
